  spring:
    application:
      name: config-server
    cloud:
      config:
        server:
          git:
            uri: https://github.com/dmv04/user-notification-config
            default-label: main
            search-paths:
              - '{application}'
              - '{application}/*'
              - circuit-breaker
            force-pull: true

  server:
    port: 8888